### ISSUE TITLE
netlify demo is down

### ISSUE THREAD

**Issue by imgntn** [saurabhdaware/visconf#2]
:)

**Comment by saurabhdaware** [comment]
Can you mention which browser you're trying from? I just tried and it is working for me

![Screenshot of netlify demo displaying the site is up](https://user-images.githubusercontent.com/30949385/73204823-b3aa3480-4165-11ea-88d0-701a561f772c.png)

**Comment by imgntn** [comment]
you have a typo in your link apparently.  it's 'netlify' not 'netflify'

**Comment by saurabhdaware** [comment]
Oh no my bad... even yesterday I spent 2 hours debugging why my environment variable is `undefined` to later find out I was writing `process.env.FAUNDADB_SECRET` instead of FAUNADB_SECRET 

Thanks for reporting, I will fix it
